[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.fuzz-prepare]
script = [
    "cargo install --force cargo-afl afl_runner",
    "cargo afl system-config",
]

[tasks.fuzz-build]
args = ["afl", "build", "--release"]
command = "cargo"
cwd = "./fuzz"

[tasks.fuzz-run]
script = [
    "aflr run -n 8 --input-dir fuzz/corpus --output-dir fuzz/tmp_fuzz_wd --target target/release/lexord_fuzz --session-name afl-fuzz --detached",
    "sleep 5",
    "aflr tui fuzz/tmp_fuzz_wd",
    "tmux kill-session -t afl-fuzz",
]
dependencies = ["fuzz-build"]
ignore_errors = true

[tasks.fuzz-min]
script = { file = "fuzz-min.sh" }

[tasks.update-golden]
cwd = "golden"
command = "cargo"
args = ["test"]
env = { "UPDATE_GOLDEN" = "1" }

[tasks.fuzz]
run_task = { name = ["fuzz-run", "fuzz-min", "update-golden"] }
