[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.fuzz-build]
args = ["afl", "build", "--release"]
command = "cargo"
cwd = "./fuzz"

[tasks.fuzz-run]
script = ["aflr run", "tmux kill-session -t afl-fuzz"]
dependencies = ["fuzz-build"]
ignore_errors = true

[tasks.fuzz-min]
script = { file = "fuzz-min.sh" }

[tasks.update-golden]
cwd = "golden"
command = "cargo"
args = ["test"]
env = { "UPDATE_GOLDEN" = "1" }

[tasks.fuzz]
run_task = { name = ["fuzz-run", "fuzz-min", "update-golden"] }
