[package]
name = "lexord-fuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
lexord = { version = "0.1.0", path = ".." }
afl = "0.15.5"
arbitrary = { version = "1.3.2", features = ["derive"] }
proc-macro2 = "1.0.81"
quote = "1.0.36"
