name: "Test"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6"
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v3
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          profile: minimal
          override: true
      - run: cargo test --all
      - run: sudo apt install -y binutils-dev libunwind-dev
      - run: cargo install cargo-bolero
      - uses: actions/cache/restore@v3
        with:
          path: tests/type_test/corpus
          key: fuzz-corpus-${{ github.run_id }}
          restore-keys: |
            fuzz-corpus-
      - run: cargo bolero test type_test -T 10min
      - run: cargo bolero reduce type_test
      - uses: actions/cache/save@v3
        if: always()
        with:
          path: tests/type_test/corpus
          key: fuzz-corpus-${{ github.run_id }}
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
